import {FilterProvider} from '@/context/phoenix-context';
import Header from '@/components/header';
import {Saira} from 'next/font/google'
import "./globals.css";

const saira = Saira({
    weight: ['300', '400', '500', '600'],
    subsets: ['latin']
});

export const metadata = {
    title: "Phoenix Shop",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={saira.className}>
        <FilterProvider>
            <Header/>
            {children}
        </FilterProvider>
        </body>
        </html>
    );
}
